CREATE TABLE `keywords` (
  `id` INTEGER NOT NULL,
  `keyword` TEXT NOT NULL,
  `classname` TEXT NOT NULL,
  `alias` TEXT NOT NULL,
  `keywordEn` TEXT NOT NULL,
  `aliasEn` TEXT NOT NULL
) ;
INSERT INTO `keywords` (`id`, `keyword`, `classname`, `alias`, `keywordEn`, `aliasEn`) VALUES
(1, 'Ćevabdžinica', 'icon-restoran', 'ćevabdžinica', 'Steak House', ''),
(2, 'Buregdžinica', 'icon-restoran', 'buregdžinica', 'Burek shop', ''),
(3, 'Slastičarna', 'icon-patisserie', 'slastičarna', 'Patisserie', ''),
(4, 'Tramvaj', 'icon-tramvaj', 'tramvaj', 'Tram', ''),
(5, 'Bus', 'icon-bus', 'bus', 'Bus', ''),
(6, 'Minibus', 'icon-bus', 'minibus', 'Minibus', ''),
(7, 'Obuća', 'icon-obuca', 'obuća', 'Footwear', ''),
(8, 'Trolejbus', 'icon-trola', 'trolejbus', 'Trolleybus', ''),
(9, 'Banka', '', 'banka', 'Bank', ''),
(10, 'Bankomat', 'icon-atm', 'bankomat', 'ATM', ''),
(11, 'Mjenjačnica', '', 'mjenjačnica', 'Currency exchange', ''),
(12, 'Parking', '', 'parking', 'Parking', ''),
(13, 'Bašta', '', 'bašta', 'Garden', ''),
(14, 'Wi - Fi', '', 'wi-fi', 'Wi - Fi', ''),
(15, 'Restoran', '', 'restoran-3', 'Restaurant', ''),
(16, 'Kafić', '', 'kafić', 'Cafe', ''),
(17, 'Ćevapi', '', 'ćevapi', 'Ćevapi', ''),
(18, 'Kafa', '', 'kafa', 'Coffee', ''),
(19, 'Dezert', '', 'dezert', 'Dessert', ''),
(20, 'Čaj', '', 'čaj', 'Tea', ''),
(21, 'Pita', '', 'pita', 'Pie', ''),
(22, 'Nacionalna kuhinja', '', 'nacionalna-kuhinja', 'National Cuisine', ''),
(25, 'Terasa', '', 'terasa', 'Terrace', ''),
(26, 'Bar', '', 'bar', 'Bar', ''),
(27, 'Recepcija', '', 'recepcija', 'Reception', ''),
(28, 'Praonica rublja', '', 'praonica-rublja', 'Laundry', ''),
(29, 'Skladište prtljaga', '', 'skladište-prtljaga', 'Storage-luggage', ''),
(30, 'Klima', '', 'klima', 'Air conditioner', ''),
(31, 'Prostor za pušače', '', 'prostor-za-pušače', 'Space for smokers', ''),
(32, 'Prostor za nepušače', '', 'prostor-za-nepušače', 'Non-smoking area', ''),
(33, 'Grijanje', '', 'grijanje', 'Heating', ''),
(34, 'Čorba', '', 'čorba', 'Soup', ''),
(35, 'Hladna predjela', '', 'hladna-predjela', 'Cold appetizer', ''),
(36, 'Pite', '', 'pite', 'Pie', ''),
(37, 'Roštilj', '', 'roštilj', 'Grill', ''),
(38, 'Salate', '', 'salate', 'Salads', ''),
(39, 'Bosanska plata', '', 'bosanska-plata', 'Bosnian wages', ''),
(40, 'Francuksa salata', '', 'francuksa-salata', 'French salad', ''),
(41, 'Masline', '', 'masline', 'Olives', ''),
(42, 'Paradajz čorba', '', 'paradajz-čorba', 'Tomato soup', ''),
(43, 'Begova čorba', '', 'begova-čorba', 'Bey''s soup', ''),
(44, 'Burek', '', 'burek', 'Burek', ''),
(45, 'Zeljanica', '', 'zeljanica', 'Spinach pie', ''),
(46, 'Sirnica', '', 'sirnica', 'Cheese pie', ''),
(47, 'Kljukuša', '', 'kljukuša', 'Kljukusa', ''),
(49, 'Crkva', 'icon-crkva', 'crkva', 'Church', ''),
(50, 'Džamija', 'icon-dzamija', 'džamija', 'Mosque', ''),
(51, 'Sinagoga', 'icon-sinagoga', 'sinagoga', 'Synagogue', ''),
(52, 'Kolači', '', 'kolači', 'Pastries', ''),
(53, 'Torta', '', 'torta', 'Cake', ''),
(54, 'Baklava', '', 'baklava', 'Baklava', ''),
(55, 'Šampita', '', 'šampita', 'Šampita', ''),
(64, 'Sunčane naočale', '', 'sunčane-naočale', 'Sunglasses', ''),
(65, 'Dioptrijske naočale', '', 'dioptrijske-naočale', 'Prescription glasses', ''),
(66, 'Kontaktna sočiva', '', 'kontaktna-sočiva', 'Contact lenses', ''),
(67, 'Oftalmoloski pregled', '', 'oftalmoloski-pregled', 'Ophthalmological examination', ''),
(68, 'Korekcijska stakla', '', 'korekcijska-stakla', 'Correction glass', ''),
(69, 'Sok', '', 'sok', 'Juice', ''),
(70, 'Limunada', '', 'limunada', 'Lemonade', ''),
(71, 'Boza', '', 'boza', 'Boza', ''),
(72, 'Papuče', '', 'papuče', 'Slippers', ''),
(73, 'Čizme', '', 'čizme', 'Boots', ''),
(74, 'Borovo', '', 'borovo', 'Borovo', ''),
(75, 'Geox', '', 'geox', 'Geox', ''),
(76, 'Bazen', 'icon-bazen', 'bazen', 'Swimming pool', ''),
(77, 'Pivo', '', 'pivo', 'Beer', ''),
(78, 'Def', 'icon-def', 'def', 'Def', ''),
(79, 'TV', '', 'tv', 'TV', ''),
(80, 'Gradska tura', '', 'gradska-tura', 'City tour', ''),
(81, 'Izlet', '', 'izlet', 'Trip', ''),
(82, 'Vodič', '', 'vodič', 'Guide', ''),
(83, 'Turizam', '', 'turizam', 'Tourism', ''),
(84, 'Obilazak grada', '', 'obilazak-grada', 'City tour', ''),
(85, 'Paraglajding', '', 'paraglajding', 'Paragliding', ''),
(86, 'Planinarenje', '', 'planinarenje', 'Mountaineering', ''),
(87, 'Vino', '', 'vino', 'Wine', ''),
(88, 'Morska kuhinja', '', 'morska-kuhinja', 'Seafood kitchen', ''),
(89, 'Morski plodovi', '', 'morski-plodovi', 'Seafood ', ''),
(90, 'Riba', '', 'riba', 'Fish', ''),
(91, 'PC', '', 'pc', 'PC', ''),
(92, 'Donje rublje', '', 'donje-rublje', 'Underwear', ''),
(93, 'Potkošulja', '', 'potkošulja', 'Undershirt', ''),
(94, 'Donje rublje za muškarce', 'icon-mrublje', 'donje-rublje-za-muškarce', 'Underwear for men', ''),
(95, 'Majica', '', 'majica', 'T-shirt', ''),
(96, 'Hlače', '', 'hlače', 'Pants', ''),
(97, 'Nargila', 'icon-noun_29679_cc', 'nargila', 'Nargila', ''),
(98, 'TV Kablovska', '', 'tv-kablovska', 'TV Cable', ''),
(99, 'Iznajmljivanje bicikla', 'icon-bicikl', 'iznajmljivanje-bicikla', 'Rent a bike', ''),
(100, 'Palačinkarnica', '', 'palačinkarnica', 'Creperie', ''),
(101, 'Pasta bar', '', 'pasta-bar', 'Pasta bar', ''),
(102, 'Sendvič bar', '', 'sendvič-bar', 'Sandwich bar', ''),
(103, 'Košulja', '', 'košulja', 'Shirt', ''),
(104, 'Trenerka', '', 'trenerka', 'Track suit', ''),
(105, 'Noćenje', '', 'noćenje', 'Overnight stay', ''),
(106, 'Spavanje', '', 'spavanje', 'Sleep', ''),
(107, 'Pansion', '', 'pansion', 'Pansion', ''),
(108, 'Prenočište', '', 'prenočište', 'Dormitory', ''),
(109, 'Kreveti', '', 'kreveti', 'Beds', ''),
(110, 'Vinoteka', '', 'vinoteka', 'Wine shop', ''),
(111, 'VINA ANDRIJA', '', 'vina-andrija', 'Wine Andrija', ''),
(112, 'Vina Matić', '', 'vina-matić', 'Wina Matic', ''),
(113, 'CARSKI VINOGRADI', '', 'carski-vinogradi', 'Imperial Vineyards', ''),
(114, 'Champagnes', '', 'champagnes', 'Champagnes', ''),
(115, 'Hotel', '', 'hotel', 'Hotel', ''),
(116, 'Gong Bao piletina', '', 'gong-bao-piletina', 'Gong Bao Chicken', ''),
(117, 'Pržena piletina sa zelenim čilijem', '', 'pržena-piletina-sa-zelenim-čilijem', 'Fried chicken with green chilli', ''),
(118, 'San Pierro sa pet kineskih začina', '', 'san-pierro-sa-pet-kineskih-začina', 'San Pierro with five chinese spices', ''),
(119, 'Kuhana riža', '', 'kuhana-riža', 'Cooked rice', ''),
(120, 'Kineska kuhinja', '', 'kineska-kuhinja', 'Chinese cuisine', ''),
(121, 'Italijanska kuhinja', '', 'italijanska-kuhinja', 'Italian cuisine', ''),
(122, 'Insalata Frutti di Mare ', '', 'insalata-frutti-di-mare', 'Insalata Frutti di Mare ', ''),
(123, 'Insalata di Ruccola', '', 'insalata-di-ruccola', 'Insalata di Ruccola', ''),
(124, 'Insalata Mista', '', 'insalata-mista', 'Insalata Mista', ''),
(125, 'Insalata Grecia', '', 'insalata-grecia', 'Insalata Grecia', ''),
(126, 'Insalata con Mozzarela Pomodoro e Rucola /', '', 'insalata-con-mozzarela-pomodoro-e-rucola-', 'Insalata con Mozzarela Pomodoro e Rucola /', ''),
(127, 'Insalata al Tono', '', 'insalata-al-tono', 'Insalata al Tono', ''),
(128, 'Insalata con Petto di Pollo', '', 'insalata-con-petto-di-pollo', 'Insalata con Petto di Pollo', ''),
(129, 'Pizza', '', 'pizza', 'Pizza', ''),
(130, 'Sladoled', '', 'sladoled', 'Ice cream', ''),
(131, 'Krompiruša', '', 'krompiruša', 'Potato pie', ''),
(132, 'Jogurt', '', 'jogurt', 'Yogurt', ''),
(133, 'Hrana', '', 'hrana', 'Food', ''),
(134, 'Karaoke', '', 'karaoke', 'Karaoke', ''),
(135, 'Apoteka', 'icon-apoteka', 'apoteka', 'Pharmacy', ''),
(136, 'Tablete', '', 'tablete', 'Tablets', ''),
(137, 'Sirup', '', 'sirup', 'Syrup', ''),
(138, 'Ekskurzije', '', 'ekskurzije', 'Excursions', ''),
(139, 'Ljetovanje', '', 'ljetovanje', 'Vacations', ''),
(140, 'Avio karte', '', 'avio-karte', 'Airline tickets', ''),
(141, 'Medeni mjesec', '', 'medeni-mjesec', 'Honeymoon', ''),
(142, 'Individualna putovanja', '', 'individualna-putovanja', 'Individual tours', ''),
(143, 'Ljeto', '', 'ljeto', 'Summer', ''),
(144, 'Albanija', '', 'albanija', 'Albania', ''),
(145, 'Grčka', '', 'grčka', 'Greece', ''),
(146, 'Bugarska', '', 'bugarska', 'Bulgaria', ''),
(147, 'Sarajevo Tekstil', '', 'sarajevo-tekstil', 'Sarajevo Tekstil', ''),
(148, 'Hostel', '', 'hostel', 'Hostel', ''),
(149, 'Smještaj', '', 'smještaj', 'Accommodation', ''),
(150, 'Muzej', '', 'muzej', 'Museum', ''),
(151, 'Knjige', '', 'knjige', 'Books', ''),
(152, 'Sevdah', '', 'sevdah', 'Sevdah', ''),
(153, 'Art', '', 'art', 'Art', ''),
(154, 'Sobe', '', 'sobe', 'Rooms', ''),
(155, 'Slastice', '', 'slastice', 'Pastry', ''),
(156, 'Med', '', 'med', 'Honey', ''),
(157, 'Začini', '', 'začini', 'Spices', ''),
(158, 'Slatki butik', '', 'slatki-butik', 'Sweet boutique', ''),
(159, 'Piletina', '', 'piletina', 'Chicken', ''),
(160, 'Aščinica', '', 'aščinica', 'Aščinica', ''),
(161, 'Jakna', '', 'jakna', 'Jacket', ''),
(162, 'Kaput', '', 'kaput', 'Coat', ''),
(163, 'Odjeća za djecu', '', 'odjeća-za-djecu', 'Children''s Clothing', ''),
(164, 'Jazz', '', 'jazz', 'Jazz', ''),
(165, 'Blues', '', 'blues', 'Blues', ''),
(166, 'Muzika uživo', '', 'muzika-uživo', 'Live Music', ''),
(167, 'Live music', '', 'live-music', 'Live music', ''),
(168, 'Kokice', '', 'kokice', 'Popcorn', ''),
(169, 'Muzika', '', 'muzika', 'Music', ''),
(170, 'Muzički instrumenti', 'icon-muzicka', 'muzički-instrumenti', 'Musical instruments', ''),
(171, 'CD-ovi', '', 'cd-ovi', 'CD-ovi', ''),
(172, 'Gitara', '', 'gitara', 'Guitar', ''),
(173, 'Bubanj', '', 'bubanj', 'Drum', ''),
(174, 'Muška odjeća', '', 'muška-odjeća', 'Menswear', ''),
(175, 'Odjeća', '', 'odjeća', 'Clothing', ''),
(176, 'Pantole', '', 'pantole', 'The pants', ''),
(177, 'Majice', '', 'majice', 'T-shirts', ''),
(178, 'Koktel', '', 'koktel', 'Cocktail', ''),
(179, 'Zabava', '', 'zabava', 'Fun', ''),
(180, 'Pub', '', 'pub', 'Pub', ''),
(181, 'Tehnika', '', 'tehnika', 'Household appliances', ''),
(182, 'Kompjuter', '', 'kompjuter', 'Computer', ''),
(183, 'Laptop', '', 'laptop', 'Laptop', ''),
(184, 'Slušalice', '', 'slušalice', 'Headset', ''),
(185, 'Mobilni telefoni', 'icon-mobitel', 'mobilni-telefoni', 'Mobile Phones', ''),
(186, 'Tableti', '', 'tableti', 'Tablets', ''),
(187, 'Info centar', 'icon-info31', 'info-centar', 'Info centar', ''),
(188, 'City tours', '', 'city-tours', 'City tours', ''),
(189, 'informacije', '', 'informacije', 'Information', ''),
(190, 'Agencija', '', 'agencija', 'Agency', ''),
(191, 'Finansije', '', 'finansije', 'Finance', ''),
(192, 'Servis', '', 'servis', 'Service', ''),
(193, 'Pljeskavica', '', 'pljeskavica', 'Burger', ''),
(194, 'Sudžukice', '', 'sudžukice', 'Sausages', ''),
(195, 'Vjerski objekat', '', 'vjerski-objekat', 'Religious building', ''),
(196, 'Piće', '', 'piće', 'Drink', ''),
(197, 'Sarajevo', '', 'sarajevo-2', 'Sarajevo', ''),
(198, 'Atrakcija ', '', 'atrakcija', 'Attraction', ''),
(199, 'Čaršija', '', 'čaršija', 'Carsija', ''),
(200, 'Baščaršija', '', 'baščaršija-3', 'Bascarsija', ''),
(201, 'Golubovi', '', 'golubovi', 'Pigeons', ''),
(202, 'Voda', '', 'voda', 'Water', ''),
(203, 'Česma', '', 'česma', 'Tap', ''),
(204, 'Lijek', '', 'lijek', 'Medicine', ''),
(205, 'Biljke', '', 'biljke', 'Plants', ''),
(206, 'Javna ustanova', 'icon-justanova', 'javna-ustanova', 'Public institution', ''),
(207, 'Putovanja', '', 'putovanja', 'Travels', ''),
(208, 'House music', '', 'house-music', 'House music', ''),
(209, 'Prodaja', '', 'prodaja', 'Selling', ''),
(210, 'Lijekovi', '', 'lijekovi', 'Medicines', ''),
(211, 'Antibiotik', '', 'antibiotik', 'Antibiotic', ''),
(212, 'Tablete za glavu', '', 'tablete-za-glavu', 'Headache pills', ''),
(213, 'Sala', '', 'sala', 'Hall', ''),
(214, 'Stomatološka ordinacija', 'icon-stomatolog', 'stomatološka-ordinacija', 'Dental clinic', ''),
(215, 'zdravlje', '', 'zdravlje', 'Health', ''),
(216, 'Konoba', '', 'konoba', 'Tavern', ''),
(217, 'Šišanje', '', 'šišanje', 'Haircut', ''),
(218, 'Frizura', '', 'frizura', 'Haircut', ''),
(219, 'Pranje kose ', '', 'pranje-kose', 'Washing hair', ''),
(220, 'Spa', '', 'spa', 'Spa', ''),
(221, 'Teretana', '', 'teretana', 'Gym', ''),
(222, 'Fitnes', 'icon-gym', 'fitnes', 'Fitness', ''),
(223, 'Olovke', '', 'olovke', 'Pencils', ''),
(224, 'Sveske', '', 'sveske', 'Notebooks', ''),
(225, 'Hamburger', '', 'hamburger', 'Hamburger', ''),
(226, 'Kursna lista', '', 'kursna-lista', 'Exchange rate', ''),
(228, 'Krediti', '', 'krediti', 'Loans', ''),
(229, 'Bezalkoholni koktel', '', 'bezalkoholni-koktel', 'Non-alcoholic cocktail', ''),
(230, 'Vjerska misa ', '', 'vjerska-misa', 'Religious Mass', ''),
(231, 'Trg', '', 'trg', 'Square', ''),
(232, 'Sportska operma', 'icon-soprema', 'sportska-operma', 'Sports equipment', ''),
(233, 'Nakit', '', 'nakit', 'Jewelry', ''),
(234, 'Naušnice', '', 'naušnice', 'Earring', ''),
(235, 'Ogrlica', '', 'ogrlica', 'Necklace', ''),
(236, 'Osiguranje', 'icon-osiguranje', 'osiguranje', 'Insurance', ''),
(237, 'Frizerski salon', 'icon-frizer', 'frizerski-salon', 'Hairdressing salon', ''),
(238, 'Kozmetika', 'icon-kozmetika', 'kozmetika', 'Cosmetics', ''),
(239, 'Predstave', '', 'predstave', 'Performances', ''),
(240, 'Izložba', '', 'izložba', 'Exhibition', ''),
(241, 'Folklor', '', 'folklor', 'Folklore', ''),
(243, 'Tamburaši', '', 'tamburaši', 'Tamburaši', ''),
(244, 'Osnovna škola', '', 'osnovna-škola', 'Elementary School', ''),
(245, 'Obrazovanje', '', 'obrazovanje-2', 'Education', ''),
(246, 'Video nadzor', '', 'video-nadzor', 'Video Surveillance', ''),
(247, '24h', '', '24h', '24h', ''),
(248, 'Fen', '', 'fen', 'Hairdryer', ''),
(249, 'Peškir', '', 'peškir', 'Towel', ''),
(250, 'Kebab', '', 'kebab', 'Kebab', ''),
(251, 'Fast food', 'icon-fastfood6', 'fast-food', 'Fast food', ''),
(252, 'Falafel', '', 'falafel', 'Falafel', ''),
(253, 'Buritto', '', 'buritto', 'Buritto', ''),
(255, 'Cheesburger', '', 'cheesburger', 'Cheesburger', ''),
(256, 'Pomfrit', '', 'pomfrit', 'French fries', ''),
(257, 'Vratnik', '', 'vratnik', 'Vratnik', ''),
(258, 'Ženska odjeća', '', 'ženska-odjeća', 'Ladieswear', ''),
(259, 'Moda', '', 'moda', 'Fashion', ''),
(260, 'Biblioteka', 'icon-knjiga', 'biblioteka', 'Library', ''),
(261, 'Izdavačka djelatnost', '', 'izdavačka-djelatnost', 'Publishing', ''),
(262, 'Centar za Menadžment i informacione tehnologije', '', 'centar-za-menadžment-i-informacione-tehnologije', 'Center for Management and Information Technology', ''),
(263, 'Poslovna akademija', '', 'poslovna-akademija', 'Business Academy', ''),
(264, 'E-Net centar ', '', 'e-net-centar', 'E-Net Center', ''),
(265, 'Kultura', '', 'kultura', 'Culture', ''),
(266, 'Centar za preduzetništvo ', '', 'centar-za-preduzetništvo', 'Center for Entrepreneurship', ''),
(267, 'Kompozicija', '', 'kompozicija', 'Composition', ''),
(268, 'Dirigovanje', '', 'dirigovanje', 'Conducting', ''),
(269, 'Solo pjevanje', '', 'solo-pjevanje', 'Solo singing', ''),
(270, 'Klavir, udaraljke, harfa', '', 'klavir-udaraljke-harfa', 'Piano, percussion, harp', ''),
(271, 'Gudački instrumenti i Gitara', '', 'gudački-instrumenti-i-gitara', 'String Instruments and Guitar', ''),
(272, 'Duvački instrumenti i Harmonika', '', 'duvački-instrumenti-i-harmonika', 'Wind Instruments and Accordion', ''),
(273, 'Muzikologija i etnomuzikologija', '', 'muzikologija-i-etnomuzikologija', 'Musicology and Ethnomusicology', ''),
(274, 'Muzička teorija i pedagogija', '', 'muzička-teorija-i-pedagogija', 'Music theory and pedagogy', ''),
(275, 'Vatrogasci', 'icon-vatrogasci', 'vatrogasci', 'Fire department', ''),
(276, 'Konzularni postupci', '', 'konzularni-postupci', 'The consular procedures', ''),
(277, 'Viza', '', 'viza', 'Visa', ''),
(278, 'Pasoš', '', 'pasoš', 'Passport', ''),
(279, 'Turkey Home', '', 'turkey-home', 'Turkey Home', ''),
(280, 'Tene', '', 'tene', 'Sneakers', ''),
(281, 'Hemijska čistionica', 'icon-hcistiona', 'hemijska-čistionica', 'Dry cleaning', ''),
(282, 'Čišćenje zavjesa ', '', 'čišćenje-zavjesa', 'Cleaning curtains', ''),
(283, 'Bojenje odjeće ', '', 'bojenje-odjeće', 'Dyeing clothes', ''),
(284, 'Krojačke usluge ', '', 'krojačke-usluge', 'Tailoring services', ''),
(285, 'Zaštita od moljaca ', '', 'zaštita-od-moljaca', 'Protection against moths', ''),
(286, 'Čišćenje vjenčanica ', '', 'čišćenje-vjenčanica', 'Cleaning wedding dress', ''),
(287, 'Servis za pranje košulja ', '', 'servis-za-pranje-košulja', 'Servis washing shirt', ''),
(288, 'Peglanje rublja ', '', 'peglanje-rublja', 'Ironing', ''),
(290, 'Antikviteti', '', 'antikviteti', 'Antiquities', ''),
(291, 'Skulpture', '', 'skulpture', 'Sculptures', ''),
(292, 'Art fotografija', '', 'art-fotografija', 'Art photography', ''),
(293, 'Kifla', '', 'kifla', 'Roll', ''),
(294, 'Hljeb', '', 'hljeb', 'Bread', ''),
(295, 'Higijena', '', 'higijena', 'Hygiene', ''),
(296, 'Štamparija', '', 'štamparija', 'Pressroom', ''),
(297, 'Print', '', 'print', 'Print', ''),
(298, 'Cvjećara', 'icon-cvijet', 'cvjećara', 'Flower shop', ''),
(299, 'Cvijeće', '', 'cvijeće', 'Flowers', ''),
(300, 'Ukrasi', '', 'ukrasi', 'Finery', ''),
(301, 'Pokloni', '', 'pokloni', 'Gifts', ''),
(302, 'Buket ', '', 'buket', 'Bouquet', ''),
(303, 'palačinci', '', 'palačinci', 'Pancakes', ''),
(304, 'Sandale', '', 'sandale', 'Sandals', ''),
(305, 'Cipele', 'icon-obuca', 'cipele', 'Shoes', ''),
(306, 'Internet', '', 'internet', 'Internet', ''),
(307, 'Internet kafić', '', 'internet-kafić', 'Internet cafe', ''),
(308, 'Tužilaštvo', '', 'tužilaštvo', 'Pprosecutor''s office', ''),
(309, 'Romani', '', 'romani', 'Novels', ''),
(310, 'Udžbenici', '', 'udžbenici', 'Textbooks', ''),
(311, 'Tužbe', '', 'tužbe', 'Lawsuits', ''),
(312, 'Pravo', '', 'pravo', 'Law', ''),
(313, 'Gas', 'icon-gas', 'gas', 'Gas', ''),
(314, 'Gorivo', '', 'gorivo', 'Fuel', ''),
(315, 'Benzinska pumpa', 'icon-benzinska', 'benzinska-pumpa', 'Gas station', ''),
(316, 'Prodavnica', '', 'prodavnica', 'Shop', ''),
(317, 'Atletika', 'icon-atletika', 'atletika', 'Athletics', ''),
(318, 'Maraton', 'icons1-Maraton', 'maraton', 'Marathon', ''),
(319, 'Kros', '', 'kros', 'Cross-country', ''),
(320, 'Hodanje', '', 'hodanje', 'Walking', ''),
(321, 'Alkohol', '', 'alkohol', 'Alcohol', ''),
(323, 'Uprava policije', '', 'uprava-policije', 'Police', ''),
(324, 'Zahtjev za izdavanje/zamjenu lične karte', '', 'zahtjev-za-izdavanje-zamjenu-lične-karte', 'The request for issuance / replacement of ID cards', ''),
(325, 'Osuđivanosti ili neosuđivanosti', '', 'osuđivanosti-ili-neosuđivanosti', 'Criminal record', ''),
(326, 'Pas', '', 'pas', 'Dog', ''),
(327, 'Mačka', '', 'mačka', 'Cat', ''),
(328, 'Ptica', '', 'ptica', 'Bird', ''),
(329, 'Papagaj', '', 'papagaj', 'Parrot', ''),
(330, 'Akvaristika', '', 'akvaristika', 'Aquarium', ''),
(331, 'Akvarijum', '', 'akvarijum', 'Aquarium', ''),
(332, 'Ribica', '', 'ribica', 'Fish', ''),
(333, 'Hrana za pse', '', 'hrana-za-pse', 'Dog''s meat', ''),
(334, 'Hrana za mace', '', 'hrana-za-mace', 'Food for cats', ''),
(335, 'Parfemi', 'icon-parfem', 'parfemi', 'Perfumes', ''),
(336, 'Duhovna škola', '', 'duhovna-škola', 'Spiritual schools', ''),
(337, 'Islam', '', 'islam', 'Islam', ''),
(338, 'Bošnjak', '', 'bošnjak', 'Bošnjak', ''),
(339, 'Gazi Husrev-beg', '', 'gazi-husrev-beg', 'Gazi Husrev-Bey', ''),
(340, 'Ferhat-beg', '', 'ferhat-beg', 'Ferhat-Bey', ''),
(341, 'Seldžuka', '', 'seldžuka', 'Seldžuka', ''),
(342, 'Zemzem', '', 'zemzem', 'Zemzem', ''),
(343, 'Laureati', '', 'laureati', 'Laureates', ''),
(344, 'Valuta', '', 'valuta', 'Currency', ''),
(345, 'Meksicka kuhinja', '', 'meksicka-kuhinja', 'Mexican cuisine', ''),
(346, 'Pogled na grad', '', 'pogled-na-grad', 'City View', ''),
(347, 'Prevoz putnika', '', 'prevoz-putnika', 'Passenger transport', ''),
(348, 'Kongresni turizam', '', 'kongresni-turizam', 'Conference tourism', ''),
(349, 'Banjalučki ćevapi', '', 'banjalučki-ćevapi', 'Banjalučki ćevapi', ''),
(350, 'Filigranska radnja', '', 'filigranska-radnja', 'Filigree store', ''),
(351, 'Otkup zlata', '', 'otkup-zlata', 'Ransom gold', ''),
(352, 'Nakit po narudžbi', '', 'nakit-po-narudžbi', 'Custom jewelry', ''),
(353, 'Opravka nakita', '', 'opravka-nakita', 'Repair of jewelery', ''),
(354, 'Plesni klub', '', 'plesni-klub', 'Dance club', ''),
(355, 'Balet', '', 'balet', 'Ballet', ''),
(356, 'Moderni ples', '', 'moderni-ples', 'Modern dance', ''),
(357, 'Salsa', '', 'salsa', 'Salsa', ''),
(358, 'Latino', '', 'latino', 'Latino', ''),
(359, 'Bilijar', 'icon-bilijar', 'bilijar', 'Billiards', ''),
(360, 'Kockarnica', '', 'kockarnica', 'Casino', ''),
(361, 'Rulet', '', 'rulet', 'Roulette', ''),
(362, 'Poker', '', 'poker', 'Poker', ''),
(363, 'Zlatar', '', 'zlatar', 'Goldsmith', ''),
(364, 'Zlatarska radnja', '', 'zlatarska-radnja', 'Goldsmith shop', ''),
(365, 'Srebro', '', 'srebro', 'Silver', ''),
(366, 'Prsten', '', 'prsten', 'Ring', ''),
(367, 'Vera', '', 'vera', 'Wedding ring', ''),
(368, 'Vjerenički prsten', '', 'vjerenički-prsten', 'Engagement ring', ''),
(369, 'Montažne kuće', '', 'montažne-kuće', 'Prefabricated house', ''),
(370, 'Stolice', '', 'stolice', 'Chairs', ''),
(371, 'Vikendice', '', 'vikendice', 'Cottages', ''),
(372, 'Moderne kuće', '', 'moderne-kuće', 'Modern houses', ''),
(373, 'SFF', 'icon-sff', 'sff', 'SFF', ''),
(374, 'Filmovi', '', 'filmovi', 'Movies', ''),
(375, 'Filmske premijere', '', 'filmske-premijere', 'Movies premiere', ''),
(376, 'Filmske nagrade', '', 'filmske-nagrade', 'Movie awards', ''),
(377, 'Srce Sarajeva', '', 'srce-sarajeva', 'Heart of Sarajevo', ''),
(378, 'Crveni tepih', 'icons-cinema65', 'crveni-tepih', 'Red carpet', ''),
(379, 'Glumci i glumice', '', 'glumci-i-glumice', 'Actors and actresses', ''),
(380, 'Povoljni krediti', '', 'povoljni-krediti', 'Cheap loans', ''),
(381, 'Kredit', '', 'kredit', 'Credit', ''),
(382, 'Otvaranje računa', '', 'otvaranje-računa', 'Account opening', ''),
(383, 'SWIFT', '', 'swift', 'SWIFT', ''),
(384, 'Western Union', '', 'western-union', 'Western Union', ''),
(385, 'Kreditna kartica', '', 'kreditna-kartica', 'Credit card', ''),
(386, 'Šoping kartica', '', 'šoping-kartica', 'Shopping card', ''),
(387, 'Cargo', '', 'cargo', 'Cargo', ''),
(388, 'Robni prevoz', '', 'robni-prevoz', 'Commodity transport', ''),
(389, 'Autodijelovi', 'icon-autodijelovi', 'autodijelovi', 'Auto parts', ''),
(390, 'Kutokozmetika', '', 'autokozmetika', 'Auto Cosmetics', ''),
(391, 'Ručak', '', 'ručak', 'Lunch', ''),
(392, 'Večera', '', 'večera', 'Dinner', ''),
(393, 'Doručak', '', 'doručak', 'Breakfast', ''),
(394, 'Istorija', '', 'istorija', 'History', ''),
(395, 'Baština', '', 'baština', 'Inheritance', ''),
(396, 'naslijeđe', '', 'naslijeđe', 'Heritage', ''),
(397, 'Bistrik', '', 'bistrik', 'Bistrik', ''),
(398, 'Institut', '', 'institut', 'Institute', ''),
(399, 'Galerija', '', 'galerija', 'Gallery', ''),
(400, 'Slike', '', 'slike', 'Paintings', ''),
(401, 'Performansi', '', 'performansi', 'Performances', ''),
(402, 'Savremena umjetnost', '', 'savremena-umjetnost', 'Contemporary art', ''),
(403, 'Telekom operater', '', 'telekom-operater', 'Telecom operator', ''),
(404, 'Polovna roba', '', 'polovna-roba', 'Used goods', ''),
(405, 'Zavod', '', 'zavod', 'Office', ''),
(406, 'Zavod za zapošljavanje', '', 'zavod-za-zapošljavanje', 'Institute for Employment', ''),
(407, 'Piva', '', 'piva', 'Beer', ''),
(408, 'Proizvodnja ', 'icon-fabrika', 'proizvodnja', 'Manufacture', ''),
(409, 'Ministarstvo', '', 'ministarstvo', 'Ministry', ''),
(410, 'Zdravstvo', '', 'zdravstvo', 'Health care', ''),
(411, 'Estetska hirurgija', 'icon-estetska', 'estetska-hirurgija', 'Plastic surgery', ''),
(412, 'Hirurgija', '', 'hirurgija', 'Surgery', ''),
(413, 'Gavrilo Princip', '', '', 'Gavrilo Princip', ''),
(414, 'Gift shop', 'icon-gift', 'gift-shop', 'Gift shop', ''),
(415, 'Prodavnica poklona', '', '', 'Gift shop', ''),
(416, 'Ručni rad', '', 'ručni-rad', 'Handwork', ''),
(417, 'Telekomunikacije', 'icon-telekomunikacije', 'telekomunikacije', 'Telecommunications', ''),
(418, 'Bijela Tabija', '', 'bijela-tabija', 'White bastion', ''),
(419, 'Tabija', '', 'tabija', 'Bastion', ''),
(420, 'Tvrđava', 'icon-castle', 'tvrđava', 'Fortress', ''),
(421, 'Izrada fotografija', '', 'izrada-fotografija', 'Creating images', ''),
(422, 'Fotografija', '', 'fotografija', 'Picture', ''),
(423, 'Prodavnica satova', 'icon-sat', 'prodavnica-satova', 'Watch store', ''),
(424, 'Turističke ture', '', 'turističke-ture', 'Travel tours', ''),
(425, 'Pošiljke', '', 'pošiljke', 'Mail', ''),
(426, 'Pošta', '', 'pošta', 'Post', ''),
(427, 'Prodavnica nakita', '', 'prodavnica-nakita', 'Jewelry store', ''),
(428, 'Gimnazija', '', 'gimnazija', 'High school', ''),
(429, 'Škola', '', 'škola', 'School', ''),
(430, 'Brokerska kuća', '', 'brokerska-kuća', 'Brokerage house', ''),
(431, 'Berza', '', 'berza', 'Stock market', ''),
(432, 'Trgovanje na berzi', '', 'trgovanje-na-berzi', 'Trading on the Stock Exchange', ''),
(433, 'Dionice', '', 'dionice', 'Shares', ''),
(434, 'Obveznice', '', 'obveznice', 'Securities', ''),
(435, 'Papučarska radnja', '', 'papučarska-radnja', 'Slipper shop', ''),
(436, 'Obrt', '', 'obrt', 'obrt', ''),
(437, 'Zanat', '', 'zanat', 'Craft', ''),
(438, 'Trend', '', 'trend', 'Trend', ''),
(439, 'Rent a car', '', 'rent-a-car', 'Rent a car', ''),
(440, 'Najam', '', 'najam', 'Rent', ''),
(441, 'Strip', 'icon-text161', 'strip', 'Comic', ''),
(442, 'Striparnica', '', 'striparnica', 'Shop for comics', ''),
(443, 'Zagor', '', 'zagor', 'Zagor', ''),
(444, 'Kablovska', '', 'kablovska', 'Cable', ''),
(445, 'Turska', '', 'turska', 'Turkey', ''),
(446, 'Tekstil', '', 'tekstil', 'Textile', ''),
(447, 'Muško odijelo', '', 'muško-odijelo', 'Man suit', ''),
(448, 'Valentino', '', 'valentino', 'Valentine''s Day', ''),
(449, 'Pollini', '', 'pollini', 'Pollini', ''),
(450, 'Javno komunalno preduzeće', '', 'javno-komunalno-preduzeće', 'Public Utility Company', ''),
(451, 'Sarajevogas', '', 'sarajevogas', 'Sarajevogas', ''),
(452, 'Rahat-lokum', '', 'rahat-lokum', 'Turkish Delight', ''),
(453, 'Tahan-halva', '', 'tahan-halva', 'Tahan-halva', ''),
(454, 'Bademi', '', 'bademi', 'Almonds', ''),
(455, 'Aranžmani', '', 'aranžmani', 'Arrangements', ''),
(456, 'Pistaći', '', 'pistaći', 'Pistachios', ''),
(457, 'Prodavnica parfema ', '', 'prodavnica-parfema', 'Shop perfume', ''),
(458, 'Parfumerija', 'icon-parfem', 'parfumerija', 'Perfumery', ''),
(459, 'Predavanja', '', 'predavanja', 'Lectures', ''),
(460, 'Ispiti', '', 'ispiti', 'Exams', ''),
(461, 'Brza hrana', '', 'brza-hrana', 'Fast food', ''),
(462, 'Antikvarnica', 'icon-antik', 'antikvarnica', 'Antique shop', ''),
(463, 'Namještaj', 'icon-namjetaj', 'namještaj', 'Furniture', ''),
(464, 'lampa', '', 'lampa', 'Lamp', ''),
(465, 'Stolica', '', 'stolica', 'Chair', ''),
(466, 'Zanatlija', '', 'zanatlija', 'Artisan', ''),
(467, 'Somun', '', 'somun', 'Flat bread', ''),
(468, 'Trafika', 'icon-sell2', 'trafika', 'Newsstand', ''),
(469, 'Novine', '', 'novine', 'Newspaper', ''),
(470, 'Cigarete', '', 'cigarete', 'Cigarettes', ''),
(471, 'Dnevna štampa', '', 'dnevna-štampa', 'Newspapers', ''),
(472, 'Štampa', 'icon-kopirnica', 'štampa', 'Press', ''),
(473, 'Magazin', '', 'magazin', 'Magazine', ''),
(474, 'Pita ispod sača', '', 'pita-ispod-sača', 'Pie under the bell', ''),
(475, 'Teletina', '', 'teletina', 'Veal', ''),
(476, 'Torte', '', 'torte', 'Cakes', ''),
(477, 'Sogandolma', '', 'sogandolma', 'Sogan dolma', ''),
(478, 'Posteljina', '', 'posteljina', 'Bedclothes', ''),
(479, 'Jastuci', '', 'jastuci', 'Cushions', ''),
(480, 'Deke', '', 'deke', 'Blankets', ''),
(481, 'Butik', '', 'butik', 'Boutique', ''),
(482, 'Marame', '', 'marame', 'Scarves', ''),
(483, 'Interijer', '', 'interijer', 'Interior', ''),
(484, 'Kuhinje', '', 'kuhinje', 'Kitchens', ''),
(485, 'Dizajn', '', 'dizajn', 'Design', ''),
(486, 'Vježbe', '', 'vježbe', 'Exercises', ''),
(487, 'Rekreacija', '', 'rekreacija', 'Recreation', ''),
(488, 'Tapetar', '', 'tapetar', 'Upholsterer', ''),
(489, 'Tapete', '', 'tapete', 'Wallpaper', ''),
(490, 'Roletne', '', 'roletne', 'Persiennes', ''),
(491, 'Korekcija obrva', '', 'korekcija-obrva', 'Eyebrow correction', ''),
(492, 'Kladionica', 'icon-kladionica', 'kladionica', 'Betting window', ''),
(493, 'Klađenje', '', 'klađenje', 'Betting', ''),
(494, 'Rezultati', '', 'rezultati', 'Results', ''),
(495, 'Pramenovi', '', 'pramenovi', 'Highlights', ''),
(496, 'Dekorater', '', 'dekorater', 'Decorator', ''),
(497, 'Vizit karte', '', 'vizit-karte', 'Business cards', ''),
(498, 'Memorandumi', '', 'memorandumi', 'Memorandum', ''),
(499, 'Letci', '', 'letci', 'Leaflets', ''),
(500, 'Brošure', '', 'brošure', 'Brochures', ''),
(501, 'Plakati', '', 'plakati', 'Posters', ''),
(502, 'Reklame', '', 'reklame', 'Advertising', ''),
(503, 'Svijetleće reklame', '', 'svijetleće-reklame', 'Illuminated advertising', ''),
(504, 'Poker aparati', '', 'poker-aparati', 'Poker machines', ''),
(505, 'Kiosok', '', 'kiosok', 'Kiosok', ''),
(506, 'Izrada ključeva', 'icon-kljuc', 'izrada-ključeva', 'Production of keys', ''),
(507, 'Zaštita vozila', '', 'zaštita-vozila', 'Protection of vehicles', ''),
(508, 'Sefovi ', '', 'sefovi', 'Safes', ''),
(509, 'Blindirana vrata ', '', 'blindirana-vrata', 'Security door', ''),
(510, 'Pecivo', '', 'pecivo', 'Pastry', ''),
(511, 'Supermarket', '', 'supermarket', 'Supermarket', ''),
(512, 'Namirnice', '', 'namirnice', 'Groceries', ''),
(513, 'Prodavnica poslastica', '', 'prodavnica-poslastica', 'Store treat', ''),
(514, 'Osiguravajuća kuća', '', 'osiguravajuća-kuća', 'Insurance company', ''),
(515, 'Putničko osiguranje', '', 'putničko-osiguranje', 'Travel insurance', ''),
(516, 'Muška obuća', '', 'muška-obuća', 'Men''s shoes', ''),
(517, 'Ženska obuća', '', 'ženska-obuća', 'Ženska obuća', ''),
(518, 'Dječija obuća', '', 'dječija-obuća', 'Dječija obuća', ''),
(519, 'Čarape', 'icon-carape', 'čarape', 'Čarape', ''),
(520, 'Kamerni teatar', '', 'kamerni-teatar', 'Kamerni teatar', ''),
(521, 'Udruženje', '', 'udruženje', 'Udruženje', ''),
(522, 'Kancelarijski materijal', '', 'kancelarijski-materijal', 'Kancelarijski materijal', ''),
(523, 'Vinarija', '', 'vinarija', 'Vinarija', ''),
(524, 'Crno vino', '', 'crno-vino', 'Crno vino', ''),
(525, 'Bjelo vino', '', 'bjelo-vino', 'Bjelo vino', ''),
(526, 'Bijelo vino', '', 'bijelo-vino', 'Bijelo vino', ''),
(527, 'Nafta', '', 'nafta', 'Nafta', ''),
(528, 'Centralna banka', '', 'centralna-banka', 'Centralna banka', ''),
(529, 'Umjetnost', '', 'umjetnost', 'Umjetnost', ''),
(530, 'Šeširi i kape', '', 'šeširi-i-kape', 'Šeširi i kape', ''),
(531, 'zahtjevi', '', 'zahtjevi', 'zahtjevi', ''),
(532, 'Šumarstvo', '', 'šumarstvo', 'Šumarstvo', ''),
(533, 'Poljoprivreda', '', 'poljoprivreda', 'Poljoprivreda', ''),
(534, 'Stolovi', '', 'stolovi', 'Stolovi', ''),
(535, 'Predsjedništvo', '', 'predsjedništvo', 'Predsjedništvo', ''),
(536, 'Grb', '', 'grb', 'Grb', ''),
(537, 'Zastava', '', 'zastava', 'Zastava', ''),
(538, 'Vanjska politika', '', 'vanjska-politika', 'Vanjska politika', ''),
(539, 'Molitva', '', 'molitva', 'Molitva', ''),
(540, 'Ezan', '', 'ezan', 'Ezan', ''),
(541, 'Općina', '', 'općina', 'Općina', ''),
(542, 'Rodni list', '', 'rodni-list', 'Rodni list', ''),
(543, 'Izvod iz matične knjige rođenih', '', 'izvod-iz-matične-knjige-rođenih', 'Izvod iz matične knjige rođenih', ''),
(544, 'Izvod iz matične knjige umrlih', '', 'izvod-iz-matične-knjige-umrlih', 'Izvod iz matične knjige umrlih', ''),
(545, 'Uvjerenje o državljanstvu', '', 'uvjerenje-o-državljanstvu', 'Uvjerenje o državljanstvu', ''),
(546, 'Uvjerenja', '', 'uvjerenja', 'Uvjerenja', ''),
(547, 'Ovjere', '', 'ovjere', 'Ovjere', ''),
(548, 'Ministarstva', '', 'ministarstva', 'Ministarstva', ''),
(549, 'Zdravstvena ustanova', '', 'zdravstvena-ustanova', 'Zdravstvena ustanova', ''),
(550, 'Ambulanta', '', 'ambulanta', 'Ambulanta', ''),
(551, 'Doktori', '', 'doktori', 'Doktori', ''),
(552, 'Pregledi', '', 'pregledi', 'Pregledi', ''),
(553, 'Dom zdravlja', 'icon-dzdravlja', 'dom-zdravlja', 'Dom zdravlja', ''),
(554, 'Policija', 'icon-policija', 'policija', 'Policija', ''),
(555, 'Univerzitet', '', 'univerzitet', 'Univerzitet', ''),
(556, 'Čitaonice', '', 'čitaonice', 'Čitaonice', ''),
(557, 'Dječija igraonica', 'icon-kids1', 'dječija-igraonica', 'Dječija igraonica', ''),
(558, 'Biljna apoteka', 'icon-apotekab', 'biljna-apoteka', 'Biljna apoteka', ''),
(559, 'Donje rublje Ž', 'icon-zrublje', 'donje-rublje-z', 'Donje rublje Ž', ''),
(560, 'Donje rublje M', 'icon-mrublje', 'donje-rublje-m', 'Donje rublje M', ''),
(561, 'Vijeće Ministara', '', 'vijeće-ministara', 'Vijeće Ministara', ''),
(562, 'Parlamentarna skupština', '', 'parlamentarna-skupština', 'Parlamentarna skupština', ''),
(563, 'Građevinska škola', '', 'građevinska-škola', 'Građevinska škola', ''),
(564, 'Tenis', '', 'tenis', 'Tenis', ''),
(565, 'Košarka', '', 'kosarka', 'Košarka', ''),
(566, 'Hokej', '', 'hokej', 'Hokej', ''),
(567, 'Fudbal', '', 'fudbal', 'Fudbal', ''),
(568, 'Nogomet', 'icon-football160', 'nogomet', 'Nogomet', ''),
(569, 'Tehnička škola', '', 'tehnička-škola', 'Tehnička škola', ''),
(570, 'Postdiplomski studij', '', 'postdiplomski-studij', 'Postdiplomski studij', ''),
(571, 'Kopirnica', 'icon-kopirnica', 'kopirnica', 'Kopirnica', ''),
(572, 'Elektrotehnika', '', 'elektrotehnika', 'Elektrotehnika', ''),
(573, 'Saobraćaj', '', 'saobraćaj', 'Saobraćaj', ''),
(574, 'Komunikacije', '', 'komunikacije', 'Komunikacije', ''),
(575, 'Farmacija', '', 'farmacija', 'Farmacija', ''),
(576, 'Kriminalistika ', '', 'kriminalistika', 'Kriminalistika ', ''),
(577, 'Kriminologija', '', 'kriminologija', 'Kriminologija', ''),
(578, 'Nauka', '', 'nauka', 'Nauka', ''),
(579, 'Sport', '', 'sport-1', 'Sport', ''),
(580, 'Mašinstvo', '', 'mašinstvo', 'Mašinstvo', ''),
(581, 'Biologija', '', 'biologija', 'Biologija', ''),
(582, 'Fizika', '', 'fizika', 'Fizika', ''),
(583, 'Geografija', '', 'geografija', 'Geografija', ''),
(584, 'Hemija', '', 'hemija', 'Hemija', ''),
(585, 'Matematika', '', 'matematika', 'Matematika', ''),
(586, 'Svadba', '', 'svadba', 'Svadba', ''),
(587, 'Vjenčanje', '', 'vjen?anje', 'Vjenčanje', ''),
(588, 'Rock', 'icon-rock', 'rock', 'Rock', ''),
(590, 'Kapa', '', 'kapa', 'Kapa', ''),
(591, 'Šešir', 'icon-kapa', 'sesir', 'Šešir', ''),
(592, 'Kancelarija', 'icon-firma', 'kancelarija', 'Kancelarija', ''),
(593, 'Trening', '', 'trening', 'Trening', ''),
(594, 'Kućni ljubimci', 'icon-ljubimci', 'kucni-ljubimci', 'Kućni ljubimci', ''),
(595, 'Radni sto', '', 'radni-sto', 'Radni sto', ''),
(596, 'Radna stolica', '', 'radna-stolica', 'Radna stolica', ''),
(598, 'Željeznička škola', '', 'željeznička-škola', 'Željeznička škola', ''),
(599, 'Inovacije', '', 'inovacije', 'Inovacije', ''),
(600, 'Razvoj', '', 'razvoj', 'Razvoj', ''),
(601, 'Ekonomska škola', '', 'ekonomska-škola', 'Ekonomska škola', ''),
(602, 'Ekonomija', '', 'ekonomija', 'Ekonomija', ''),
(603, 'Katoličanstvo', 'icon-crkvak', 'katolicanstvo', 'Katoličanstvo', ''),
(604, 'Pravoslavlje', 'icon-crkvap', 'pravoslavlje', 'Pravoslavlje', ''),
(605, 'CIPS', 'icon-cips', 'cips', 'CIPS', ''),
(606, 'Penziono osiguranje', '', 'penziono-osiguranje', 'Penziono osiguranje', ''),
(607, 'Invalidsko osiguranje', '', 'invalidsko-osiguranje', 'Invalidsko osiguranje', ''),
(608, 'NoVello', '', 'novello', 'NoVello', ''),
(609, 'Igra', '', 'igra', 'Igra', ''),
(610, 'Odmor', '', 'odmor', 'Odmor', ''),
(611, 'Priroda', '', 'priroda', 'Priroda', ''),
(612, 'Veterina', '', 'veterina', 'Veterina', ''),
(613, 'Edukacija', '', 'edukacija', 'Edukacija', ''),
(614, 'Malta', '', 'malta', 'Malta', ''),
(615, 'Zippo', '', 'zippo', 'Zippo', ''),
(616, 'Elektronske cigarete', '', 'elektronske-cigarete', 'Elektronske cigarete', ''),
(617, 'Donje rublje za žene', 'icon-zrublje', 'donje-rublje-za-žene', 'Donje rublje za žene', ''),
(618, 'Kuglana', '', 'kuglana', 'Kuglana', ''),
(619, 'Proteini', '', 'proteini', 'Proteini', ''),
(620, 'Amino kiseline', '', 'amino-kiseline', 'Amino kiseline', ''),
(621, 'Kreatin', '', 'kreatin', 'Kreatin', ''),
(622, 'Glutamini', '', 'glutamini', 'Glutamini', ''),
(625, 'Bijela tehnika', '', 'bijela-tehnika', 'Bijela tehnika', ''),
(626, 'Bolnica', 'icon-dzdravlja', 'bolnica', 'Bolnica', ''),
(627, 'Liječenje', '', 'liječenje', 'Liječenje', ''),
(628, 'Operacije', '', 'operacije', 'Operacije', ''),
(629, 'Poliklinika', 'icon-poliklinika', 'poliklinika', 'Poliklinika', ''),
(630, 'Stomatologija', '', 'stomatologija', 'Stomatologija', ''),
(631, 'Ginekologija', '', 'ginekologija', 'Ginekologija', ''),
(632, 'Opšta hirurgija', '', 'opšta-hirurgija', 'Opšta hirurgija', ''),
(633, 'Pedijatrija', '', 'pedijatrija', 'Pedijatrija', ''),
(634, 'Kardiologija', '', 'kardiologija', 'Kardiologija', ''),
(635, 'Televizija', '', 'televizija', 'Televizija', ''),
(636, 'Emitovanja', '', 'emitovanje', 'Emitovanja', ''),
(637, 'Programi', '', 'programi', 'Programi', ''),
(638, 'Pravosuđe', '', 'pravosuđe', 'Pravosuđe', ''),
(639, 'Presude', '', 'presude', 'Presude', ''),
(640, 'Video igrice', '', 'video-igrice', 'Video igrice', ''),
(641, 'PlayStation', '', 'playstation', 'PlayStation', ''),
(642, 'Xbox', '', 'xbox', 'Xbox', ''),
(643, 'Konzole i igrice', '', 'konzole-i-igrice', 'Konzole i igrice', ''),
(644, 'Sapuni', '', 'sapuni', 'Sapuni', ''),
(645, 'Apple', '', 'apple', 'Apple', ''),
(646, 'iPad', '', 'ipad', 'iPad', ''),
(647, 'iPhone', '', 'iphone', 'iPhone', ''),
(648, 'McBook', '', 'mcbook', 'McBook', ''),
(649, 'Pedikura', '', 'pedikura', 'Pedikura', ''),
(650, 'Manikura', '', 'manikura', 'Manikura', ''),
(651, 'Masaža', '', 'masaža', 'Masaža', ''),
(652, 'Depilacija', '', 'depilacija', 'Depilacija', ''),
(653, 'Lifting lica', '', 'lifting-lica', 'Lifting lica', ''),
(654, 'Kaligrafija', '', 'kaligrafija', 'Kaligrafija', ''),
(655, 'Kurs arapskog jezika', '', 'kurs-arapskog-jezika', 'Kurs arapskog jezika', ''),
(657, 'Krojački salon', '', 'krojački-salon', 'Krojački salon', ''),
(658, 'Građevinski materijal', '', 'građevinski-materijal', 'Građevinski materijal', ''),
(659, 'Laminati', '', 'laminati', 'Laminati', ''),
(660, 'Distribucija', '', 'distribucija', 'Distribucija', ''),
(661, 'Trgovine', '', 'trgovine', 'Trgovine', ''),
(662, 'Kulturni centar', '', 'kulturni-centar', 'Kulturni centar', ''),
(663, 'Lječilište', '', 'lječilište', 'Lječilište', ''),
(664, 'Banja', '', 'banja', 'Banja', ''),
(665, 'Plivanje', '', 'plivanje', 'Plivanje', ''),
(666, 'Svadbeni salon', '', 'svadbeni-salon', 'Svadbeni salon', ''),
(667, 'Vrtić', 'icon-vrtic', 'vrtić', 'Vrtić', ''),
(668, 'Dječiji vrtić', 'icon-vrtic', 'dječiji-vrtić', 'Dječiji vrtić', ''),
(669, 'Obdanište', '', 'obdanište', 'Obdanište', ''),
(670, 'Dodaci ishrani', '', 'dodaci-ishrani', 'Dodaci ishrani', ''),
(671, 'Igračke za bebe', 'icon-kids1', 'igračke-za-bebe', 'Igračke za bebe', ''),
(672, 'Ženske čarape ', '', 'ženske-čarape', 'Ženske čarape ', ''),
(673, 'Ženski veš', '', 'ženski-veš', 'Ženski veš', ''),
(674, 'Kineska ambasada', '', 'kineska-ambasada', 'Kineska ambasada', ''),
(675, 'Nastava', '', 'nastava', 'Nastava', ''),
(676, 'Vlada', '', 'vlada', 'Vlada', ''),
(677, 'Uredi i službe', '', 'uredi-i-službe', 'Uredi i službe', ''),
(678, 'Zakoni', '', 'zakoni', 'Zakoni', ''),
(679, 'Web', 'icon-usluge', 'web', 'Web', ''),
(681, 'Fudbalski stadion', '', 'fudbalski-stadion', 'Fudbalski stadion', ''),
(682, 'Asim Ferhatović - Hase', '', 'asim-ferhatović-hase', 'Asim Ferhatović - Hase', ''),
(683, 'Ivica Osim', '', 'ivica-osim', 'Ivica Osim', ''),
(684, 'Amar Osim', '', 'amar-osim', 'Amar Osim', ''),
(685, 'Dolina ćupova', '', 'dolina-ćupova', 'Dolina ćupova', ''),
(686, 'Željo', '', 'željo', 'Željo', ''),
(687, 'Aerodrom', 'icon-aero', 'aerodrom', 'Aerodrom', ''),
(688, 'Judaizam', 'icon-jevrej', 'judaizam', 'Judaizam', ''),
(689, 'Javno preduzeće', '', 'javno-preduzeće', 'Javno preduzeće', ''),
(690, 'Konsultantske usluge', '', 'konsultantske-usluge', 'Konsultantske usluge', ''),
(691, 'Consulting', '', 'consulting', 'Consulting', ''),
(692, 'Video produkcija', '', 'video-produkcija', 'Video produkcija', ''),
(693, 'Dizajn studio', '', 'dizajn-studio', 'Dizajn studio', ''),
(694, 'Ginekolog', 'icon-ginekolog', 'ginekolog', 'Ginekolog', ''),
(695, 'Perinatološka služba', '', 'perinatološka-služba', 'Perinatološka služba', ''),
(696, 'Endokrinološka služba', '', 'endokrinološka-služba', 'Endokrinološka služba', ''),
(697, 'Citologija', '', 'citologija', 'Citologija', ''),
(698, 'Filozofija', '', 'filozofija', 'Filozofija', ''),
(699, 'Volonteri', '', 'volonteri', 'Volonteri', ''),
(700, 'Sarajevo Film Festival', '', 'sarajevo-film-festival', 'Sarajevo Film Festival', ''),
(701, 'SFF Kafić', 'icon-kafa-sff', 'sff-kafić', 'SFF Kafić', ''),
(702, 'SFF Pivnica', 'icon-pub-sff', 'sff-pivnica', 'SFF Pivnica', ''),
(703, 'SFF Muzej', 'icon-museum33-sff', 'sff-muzej', 'SFF Muzej', ''),
(704, 'Mediteranska kuhinja', '', 'mediteranska-kuhinja', 'Mediteranska kuhinja', ''),
(705, 'SFF Restoran', 'icon-restoran-sff', 'sff-restoran', 'SFF Restoran', ''),
(706, 'SFF Vino', 'icon-wine22-sff', 'sff-vino', 'SFF Vino', ''),
(707, 'SFF Trg', 'icons-circus', 'sff-trg', 'SFF Trg', ''),
(708, 'SFF Box', 'icon-info31-sff', 'sff-box', 'SFF Box', ''),
(709, 'Lord Somersby''s', 'icon-lord', 'lord-somersby''s', 'Lord Somersby''s', ''),
(710, 'SPA Centar', 'icons-vello', 'spa-centar', 'SPA Centar', ''),
(711, 'Njega tijela', '', 'njega-tijela', 'Njega tijela', ''),
(712, 'Masaže', '', 'masaže', 'Masaže', ''),
(713, 'Njega lica', '', 'njega-lica', 'Njega lica', ''),
(714, 'SFF Crveni tepih', '', 'sff-crveni-tepih', 'SFF Crveni tepih', ''),
(715, 'Nomas Vello', 'icons-vello', 'nomas-vello', 'Nomas Vello', ''),
(716, 'Fotoepilacija', 'icons-vello', 'fotoepilacija', 'Fotoepilacija', ''),
(717, 'Fotopodmlađivanje', '', 'fotopodmlađivanje', 'Fotopodmlađivanje', ''),
(718, 'Anticelulitni tretmani', '', 'anticelulitni-tretmani', 'Anticelulitni tretmani', ''),
(719, 'No+Vello', '', 'no-vello-1', 'No+Vello', ''),
(720, 'Refreshment', 'icons1-osvjezenje', 'refreshment', 'Refreshment', ''),
(721, 'Youth Film Festival', '', 'youth-film-festival', 'Youth Film Festival', ''),
(722, 'YFF', 'icon-sff', 'yff', 'YFF', ''),
(723, 'Pet', 'icons1-Pet', 'pet', 'Pet', ''),
(724, 'Deset', 'icons1-Deset', 'deset', 'Deset', ''),
(725, '15', 'icons1-Petnaest', '15', '15', ''),
(726, '20', 'icons1-Dvadeset', '20', '20', ''),
(727, 'Lijevo', 'icons1-next21L', 'l', 'Lijevo', ''),
(728, 'Gore', 'icons1-next21G', 'gore', 'Gore', ''),
(729, 'Desno', 'icons1-next21D', 'desno', 'Desno', ''),
(730, 'Dole', 'icons1-next21Do', 'dole', 'Dole', ''),
(731, 'Nevidljiv', '', 'nevidljiv', 'Nevidljiv', ''),
(732, 'Lasersko skidanje dioptrijeje', '', 'lasersko-skidanje-dioptrijeje', 'Lasersko skidanje dioptrijeje', ''),
(733, 'Operacija mrene', '', 'operacija-mrene', 'Operacija mrene', ''),
(734, 'Bolesti makule', '', 'bolesti-makule', 'Bolesti makule', ''),
(735, 'Autoškola', 'icon-askola', 'autoskola', 'Autoškola', ''),
(736, 'Grupna kupovina', '', 'grupna-kupovina', 'Grupna kupovina', ''),
(737, 'Nekretnine', '', 'nekretnine', 'Nekretnine', ''),
(738, 'Prodaje stanova', '', 'prodaje-stanova', 'Prodaje stanova', ''),
(739, 'Skijanje', '', 'skijanje', '', ''),
(740, 'Athitektura', '', 'athitektura', '', ''),
(741, 'Arhitektura', '', 'arhitektura', '', ''),
(742, 'Olimpijada', '', 'olimpijada', '', ''),
(743, 'Srebrenica', '', 'srebrenica', '', ''),
(744, 'Park', '', 'park-2', '', ''),
(745, 'Zoološki vrt', '', 'zoološki-vrt', '', ''),
(746, 'Životinje', '', 'životinje', '', ''),
(747, 'vodopad', '', 'vodopad', '', ''),
(748, 'Izletište', '', 'izletište', '', ''),
(749, 'šetalište', '', 'šetalište', '', ''),
(750, 'prirodno nasljeđe', '', 'prirodno-nasljeđe', '', ''),
(751, 'vidikovac', '', 'vidikovac', '', ''),
(752, 'planina', '', 'planina', '', ''),
(753, 'Računovodstvo', '', 'računovodstvo', '', ''),
(754, 'Revizija', '', 'revizija', '', ''),
(755, 'Savjetovanje', '', 'savjetovanje', '', ''),
(756, 'Mediji', '', 'mediji', '', ''),
(757, 'Internet portal', '', 'internet-portal', '', ''),
(758, 'Novosti', '', 'novosti', '', ''),
(759, 'Presvlake', '', 'presvlake', '', ''),
(760, 'Autoindustrija', '', 'autoindustrija', '', ''),
(761, 'Garaža', '', 'garaža', '', ''),
(762, 'Marketing', 'icon-uslugea', 'marketing', '', ''),
(763, 'parlament', 'parlament', 'parlament', '', ''),
(764, 'Prodaja automobila', '', 'prodaja-automobila', '', '') ;